/** @type {import('tailwindcss').Config} */
export default {
  prefix: "mtx-",
  darkMode: ["class"],
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  safelist: ["dark"],
  theme: {
    extend: {
      spacing: {
        2.5: "0.625rem",
        3.5: "0.875rem",
        4.5: "1.125rem",
        5.5: "1.375rem",
        7.5: "1.875rem",
        8.5: "2.125rem",
      },
      borderRadius: {
        lg: "var(--mtx-radius)",
        md: "calc(var(--mtx-radius) - 2px)",
        sm: "calc(var(--mtx-radius) - 4px)",
      },
      borderWidth: {
        3: "3px",
      },
      outlineOffset: {
        3: "3px",
      },
      colors: {
        background: "hsl(var(--mtx-background))",
        foreground: "hsl(var(--mtx-foreground))",
        card: {
          DEFAULT: "hsl(var(--mtx-card))",
          foreground: "hsl(var(--mtx-card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--mtx-popover))",
          foreground: "hsl(var(--mtx-popover-foreground))",
        },
        primary: {
          25: "hsl(var(--mtx-primary-25))",
          50: "hsl(var(--mtx-primary-50))",
          100: "hsl(var(--mtx-primary-100))",
          200: "hsl(var(--mtx-primary-200))",
          300: "hsl(var(--mtx-primary-300))",
          400: "hsl(var(--mtx-primary-400))",
          500: "hsl(var(--mtx-primary-500))",
          600: "hsl(var(--mtx-primary-600))",
          700: "hsl(var(--mtx-primary-700))",
          800: "hsl(var(--mtx-primary-800))",
          900: "hsl(var(--mtx-primary-900))",
          DEFAULT: "hsl(var(--mtx-primary))",
          foreground: "hsl(var(--mtx-primary-foreground))",
        },
        secondary: {
          50: "hsl(var(--mtx-secondary-50))",
          100: "hsl(var(--mtx-secondary-100))",
          200: "hsl(var(--mtx-secondary-200))",
          300: "hsl(var(--mtx-secondary-300))",
          400: "hsl(var(--mtx-secondary-400))",
          500: "hsl(var(--mtx-secondary-500))",
          600: "hsl(var(--mtx-secondary-600))",
          700: "hsl(var(--mtx-secondary-700))",
          800: "hsl(var(--mtx-secondary-800))",
          DEFAULT: "hsl(var(--mtx-secondary))",
          foreground: "hsl(var(--mtx-secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--mtx-muted))",
          foreground: "hsl(var(--mtx-muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--mtx-accent))",
          foreground: "hsl(var(--mtx-accent-foreground))",
        },
        danger: {
          200: "hsl(var(--mtx-danger-200))",
          300: "hsl(var(--mtx-danger-300))",
          400: "hsl(var(--mtx-danger-400))",
          500: "hsl(var(--mtx-danger-500))",
          600: "hsl(var(--mtx-danger-600))",
          700: "hsl(var(--mtx-danger-700))",
          800: "hsl(var(--mtx-danger-800))",
          DEFAULT: "hsl(var(--mtx-danger))",
          foreground: "hsl(var(--mtx-danger-foreground))",
        },
        success: {
          50: "hsl(var(--mtx-success-50))",
          200: "hsl(var(--mtx-success-200))",
          300: "hsl(var(--mtx-success-300))",
          400: "hsl(var(--mtx-success-400))",
          500: "hsl(var(--mtx-success-500))",
          600: "hsl(var(--mtx-success-600))",
          700: "hsl(var(--mtx-success-700))",
          800: "hsl(var(--mtx-success-800))",
          DEFAULT: "hsl(var(--mtx-success))",
          foreground: "hsl(var(--mtx-success-foreground))",
        },
        warning: {
          200: "hsl(var(--mtx-warning-200))",
          300: "hsl(var(--mtx-warning-300))",
          400: "hsl(var(--mtx-warning-400))",
          500: "hsl(var(--mtx-warning-500))",
          600: "hsl(var(--mtx-warning-600))",
          700: "hsl(var(--mtx-warning-700))",
          800: "hsl(var(--mtx-warning-800))",
          DEFAULT: "hsl(var(--mtx-warning-500))",
          foreground: "hsl(var(--mtx-warning-foreground))",
        },
        info: {
          200: "hsl(var(--mtx-info-200))",
          300: "hsl(var(--mtx-info-300))",
          400: "hsl(var(--mtx-info-400))",
          500: "hsl(var(--mtx-info-500))",
          600: "hsl(var(--mtx-info-600))",
          700: "hsl(var(--mtx-info-700))",
          DEFAULT: "hsl(var(--mtx-info-500))",
          foreground: "hsl(var(--mtx-info-foreground))",
        },
        gray: {
          DEFAULT: "hsl(var(--mtx-gray-500))",
          0: "hsl(var(--mtx-gray-0))",
          50: "hsl(var(--mtx-gray-50))",
          100: "hsl(var(--mtx-gray-100))",
          200: "hsl(var(--mtx-gray-200))",
          300: "hsl(var(--mtx-gray-300))",
          400: "hsl(var(--mtx-gray-400))",
          500: "hsl(var(--mtx-gray-500))",
          600: "hsl(var(--mtx-gray-600))",
          700: "hsl(var(--mtx-gray-700))",
          800: "hsl(var(--mtx-gray-800))",
        },
        text: {
          DEFAULT: "hsl(var(--mtx-text-500))",
          100: "hsl(var(--mtx-text-100))",
          200: "hsl(var(--mtx-text-200))",
          300: "hsl(var(--mtx-text-300))",
          400: "hsl(var(--mtx-text-400))",
          500: "hsl(var(--mtx-text-500))",
          600: "hsl(var(--mtx-text-600))",
          700: "hsl(var(--mtx-text-700))",
          800: "hsl(var(--mtx-text-800))",
        },
        purple: {
          DEFAULT: "hsl(var(--mtx-purple-500))",
          100: "hsl(var(--mtx-purple-100))",
          200: "hsl(var(--mtx-purple-200))",
          300: "hsl(var(--mtx-purple-300))",
          400: "hsl(var(--mtx-purple-400))",
          500: "hsl(var(--mtx-purple-500))",
          600: "hsl(var(--mtx-purple-600))",
          700: "hsl(var(--mtx-purple-700))",
        },
        coral: {
          100: "hsl(var(--mtx-coral-100))",
          200: "hsl(var(--mtx-coral-200))",
          300: "hsl(var(--mtx-coral-300))",
          400: "hsl(var(--mtx-coral-400))",
          500: "hsl(var(--mtx-coral-500))",
          600: "hsl(var(--mtx-coral-600))",
          700: "hsl(var(--mtx-coral-700))",
          DEFAULT: "hsl(var(--mtx-coral-500))",
        },
        lime: {
          100: "hsl(var(--mtx-lime-100))",
          200: "hsl(var(--mtx-lime-200))",
          300: "hsl(var(--mtx-lime-300))",
          400: "hsl(var(--mtx-lime-400))",
          500: "hsl(var(--mtx-lime-500))",
          600: "hsl(var(--mtx-lime-600))",
          700: "hsl(var(--mtx-lime-700))",
          DEFAULT: "hsl(var(--mtx-lime-500))",
        },
        turquoise: {
          100: "hsl(var(--mtx-turquoise-100))",
          200: "hsl(var(--mtx-turquoise-200))",
          300: "hsl(var(--mtx-turquoise-300))",
          400: "hsl(var(--mtx-turquoise-400))",
          500: "hsl(var(--mtx-turquoise-500))",
          600: "hsl(var(--mtx-turquoise-600))",
          700: "hsl(var(--mtx-turquoise-700))",
          DEFAULT: "hsl(var(--mtx-turquoise-500))",
        },
        border: "hsl(var(--mtx-border))",
        input: "hsl(var(--mtx-input))",
        ring: "hsl(var(--mtx-ring))",
        chart: {
          1: "hsl(var(--mtx-chart-1))",
          2: "hsl(var(--mtx-chart-2))",
          3: "hsl(var(--mtx-chart-3))",
          4: "hsl(var(--mtx-chart-4))",
          5: "hsl(var(--mtx-chart-5))",
        },
      },
      boxShadow: {
        card: "var(--mtx-shadow-card)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },

          to: {
            height: "0",
          },
        },
        "collapsible-down": {
          from: { height: "0" },
          to: { height: "var(--radix-collapsible-content-height)" },
        },
        "collapsible-up": {
          from: { height: "var(--radix-collapsible-content-height)" },
          to: { height: "0" },
        },
        "slide-from-bottom": {
          "0%": { transform: "translateY(100%)" },
          "100%": { transform: "translateY(0)" },
        },
        "slide-to-bottom": {
          "0%": { transform: "translateY(0)" },
          "100%": { transform: "translateY(100%)" },
        },
        "input-open": {
          "0%": { width: "0" },
          "100%": { width: "100%" },
        },
        "input-close": {
          "0%": { width: "100%" },
          "100%": { width: "0", opacity: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "collapsible-down": "collapsible-down 0.2s ease-out",
        "collapsible-up": "collapsible-up 0.2s ease-out",
        "slide-from-bottom": "slide-from-bottom 0.50s cubic-bezier(0.32,0.72,0,1) forwards",
        "slide-to-bottom": "slide-to-bottom 0.50s cubic-bezier(0.32,0.72,0,1) forwards",
        "input-open": "input-open 0.20s ease-out forwards",
        "input-close": "input-close 0.20s ease-out forwards",
      },
      backdropContrast: {
        300: "3",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
