/** @type {import('tailwindcss').Config} */
export default {
  prefix: "mtx-",
  darkMode: ["class"],
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  safelist: ["dark"],
  theme: {
    extend: {
      spacing: {
        2.5: "0.625rem",
        3.5: "0.875rem",
        4.5: "1.125rem",
        5.5: "1.375rem",
        7.5: "1.875rem",
        8.5: "2.125rem",
      },
      borderRadius: {
        lg: "var(--mtx-radius)",
        md: "calc(var(--mtx-radius) - 2px)",
        sm: "calc(var(--mtx-radius) - 4px)",
      },
      borderWidth: {
        3: "3px",
      },
      outlineOffset: {
        3: "3px",
      },
      colors: {
        background: "oklch(var(--mtx-background) / <alpha-value>)",
        foreground: "oklch(var(--mtx-foreground) / <alpha-value>)",
        card: {
          DEFAULT: "oklch(var(--mtx-card) / <alpha-value>)",
          foreground: "oklch(var(--mtx-card-foreground) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "oklch(var(--mtx-popover) / <alpha-value>)",
          foreground: "oklch(var(--mtx-popover-foreground) / <alpha-value>)",
        },
        primary: {
          25: "oklch(var(--mtx-primary-25) / <alpha-value>)",
          50: "oklch(var(--mtx-primary-50) / <alpha-value>)",
          100: "oklch(var(--mtx-primary-100) / <alpha-value>)",
          200: "oklch(var(--mtx-primary-200) / <alpha-value>)",
          300: "oklch(var(--mtx-primary-300) / <alpha-value>)",
          400: "oklch(var(--mtx-primary-400) / <alpha-value>)",
          500: "oklch(var(--mtx-primary-500) / <alpha-value>)",
          600: "oklch(var(--mtx-primary-600) / <alpha-value>)",
          700: "oklch(var(--mtx-primary-700) / <alpha-value>)",
          800: "oklch(var(--mtx-primary-800) / <alpha-value>)",
          900: "oklch(var(--mtx-primary-900) / <alpha-value>)",
          DEFAULT: "oklch(var(--mtx-primary) / <alpha-value>)",
          foreground: "oklch(var(--mtx-primary-foreground) / <alpha-value>)",
        },
        secondary: {
          50: "oklch(var(--mtx-secondary-50) / <alpha-value>)",
          100: "oklch(var(--mtx-secondary-100) / <alpha-value>)",
          200: "oklch(var(--mtx-secondary-200) / <alpha-value>)",
          300: "oklch(var(--mtx-secondary-300) / <alpha-value>)",
          400: "oklch(var(--mtx-secondary-400) / <alpha-value>)",
          500: "oklch(var(--mtx-secondary-500) / <alpha-value>)",
          600: "oklch(var(--mtx-secondary-600) / <alpha-value>)",
          700: "oklch(var(--mtx-secondary-700) / <alpha-value>)",
          800: "oklch(var(--mtx-secondary-800) / <alpha-value>)",
          DEFAULT: "oklch(var(--mtx-secondary) / <alpha-value>)",
          foreground: "oklch(var(--mtx-secondary-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "oklch(var(--mtx-muted) / <alpha-value>)",
          foreground: "oklch(var(--mtx-muted-foreground) / <alpha-value>)",
        },
        accent: {
          DEFAULT: "oklch(var(--mtx-accent) / <alpha-value>)",
          foreground: "oklch(var(--mtx-accent-foreground) / <alpha-value>)",
        },
        danger: {
          200: "oklch(var(--mtx-danger-200) / <alpha-value>)",
          300: "oklch(var(--mtx-danger-300) / <alpha-value>)",
          400: "oklch(var(--mtx-danger-400) / <alpha-value>)",
          500: "oklch(var(--mtx-danger-500) / <alpha-value>)",
          600: "oklch(var(--mtx-danger-600) / <alpha-value>)",
          700: "oklch(var(--mtx-danger-700) / <alpha-value>)",
          800: "oklch(var(--mtx-danger-800) / <alpha-value>)",
          DEFAULT: "oklch(var(--mtx-danger) / <alpha-value>)",
          foreground: "oklch(var(--mtx-danger-foreground) / <alpha-value>)",
        },
        success: {
          50: "oklch(var(--mtx-success-50) / <alpha-value>)",
          200: "oklch(var(--mtx-success-200) / <alpha-value>)",
          300: "oklch(var(--mtx-success-300) / <alpha-value>)",
          400: "oklch(var(--mtx-success-400) / <alpha-value>)",
          500: "oklch(var(--mtx-success-500) / <alpha-value>)",
          600: "oklch(var(--mtx-success-600) / <alpha-value>)",
          700: "oklch(var(--mtx-success-700) / <alpha-value>)",
          800: "oklch(var(--mtx-success-800) / <alpha-value>)",
          DEFAULT: "oklch(var(--mtx-success) / <alpha-value>)",
          foreground: "oklch(var(--mtx-success-foreground) / <alpha-value>)",
        },
        warning: {
          200: "oklch(var(--mtx-warning-200) / <alpha-value>)",
          300: "oklch(var(--mtx-warning-300) / <alpha-value>)",
          400: "oklch(var(--mtx-warning-400) / <alpha-value>)",
          500: "oklch(var(--mtx-warning-500) / <alpha-value>)",
          600: "oklch(var(--mtx-warning-600) / <alpha-value>)",
          700: "oklch(var(--mtx-warning-700) / <alpha-value>)",
          800: "oklch(var(--mtx-warning-800) / <alpha-value>)",
          DEFAULT: "oklch(var(--mtx-warning-500) / <alpha-value>)",
          foreground: "oklch(var(--mtx-warning-foreground) / <alpha-value>)",
        },
        info: {
          200: "oklch(var(--mtx-info-200) / <alpha-value>)",
          300: "oklch(var(--mtx-info-300) / <alpha-value>)",
          400: "oklch(var(--mtx-info-400) / <alpha-value>)",
          500: "oklch(var(--mtx-info-500) / <alpha-value>)",
          600: "oklch(var(--mtx-info-600) / <alpha-value>)",
          700: "oklch(var(--mtx-info-700) / <alpha-value>)",
          DEFAULT: "oklch(var(--mtx-info-500) / <alpha-value>)",
          foreground: "oklch(var(--mtx-info-foreground) / <alpha-value>)",
        },
        gray: {
          DEFAULT: "oklch(var(--mtx-gray-500) / <alpha-value>)",
          0: "oklch(var(--mtx-gray-0) / <alpha-value>)",
          50: "oklch(var(--mtx-gray-50) / <alpha-value>)",
          100: "oklch(var(--mtx-gray-100) / <alpha-value>)",
          200: "oklch(var(--mtx-gray-200) / <alpha-value>)",
          300: "oklch(var(--mtx-gray-300) / <alpha-value>)",
          400: "oklch(var(--mtx-gray-400) / <alpha-value>)",
          500: "oklch(var(--mtx-gray-500) / <alpha-value>)",
          600: "oklch(var(--mtx-gray-600) / <alpha-value>)",
          700: "oklch(var(--mtx-gray-700) / <alpha-value>)",
          800: "oklch(var(--mtx-gray-800) / <alpha-value>)",
        },
        text: {
          DEFAULT: "oklch(var(--mtx-text-500) / <alpha-value>)",
          100: "oklch(var(--mtx-text-100) / <alpha-value>)",
          200: "oklch(var(--mtx-text-200) / <alpha-value>)",
          300: "oklch(var(--mtx-text-300) / <alpha-value>)",
          400: "oklch(var(--mtx-text-400) / <alpha-value>)",
          500: "oklch(var(--mtx-text-500) / <alpha-value>)",
          600: "oklch(var(--mtx-text-600) / <alpha-value>)",
          700: "oklch(var(--mtx-text-700) / <alpha-value>)",
          800: "oklch(var(--mtx-text-800) / <alpha-value>)",
        },
        purple: {
          DEFAULT: "oklch(var(--mtx-purple-500) / <alpha-value>)",
          100: "oklch(var(--mtx-purple-100) / <alpha-value>)",
          200: "oklch(var(--mtx-purple-200) / <alpha-value>)",
          300: "oklch(var(--mtx-purple-300) / <alpha-value>)",
          400: "oklch(var(--mtx-purple-400) / <alpha-value>)",
          500: "oklch(var(--mtx-purple-500) / <alpha-value>)",
          600: "oklch(var(--mtx-purple-600) / <alpha-value>)",
          700: "oklch(var(--mtx-purple-700) / <alpha-value>)",
        },
        coral: {
          100: "oklch(var(--mtx-coral-100) / <alpha-value>)",
          200: "oklch(var(--mtx-coral-200) / <alpha-value>)",
          300: "oklch(var(--mtx-coral-300) / <alpha-value>)",
          400: "oklch(var(--mtx-coral-400) / <alpha-value>)",
          500: "oklch(var(--mtx-coral-500) / <alpha-value>)",
          600: "oklch(var(--mtx-coral-600) / <alpha-value>)",
          700: "oklch(var(--mtx-coral-700) / <alpha-value>)",
          DEFAULT: "oklch(var(--mtx-coral-500) / <alpha-value>)",
        },
        lime: {
          100: "oklch(var(--mtx-lime-100) / <alpha-value>)",
          200: "oklch(var(--mtx-lime-200) / <alpha-value>)",
          300: "oklch(var(--mtx-lime-300) / <alpha-value>)",
          400: "oklch(var(--mtx-lime-400) / <alpha-value>)",
          500: "oklch(var(--mtx-lime-500) / <alpha-value>)",
          600: "oklch(var(--mtx-lime-600) / <alpha-value>)",
          700: "oklch(var(--mtx-lime-700) / <alpha-value>)",
          DEFAULT: "oklch(var(--mtx-lime-500) / <alpha-value>)",
        },
        turquoise: {
          100: "oklch(var(--mtx-turquoise-100) / <alpha-value>)",
          200: "oklch(var(--mtx-turquoise-200) / <alpha-value>)",
          300: "oklch(var(--mtx-turquoise-300) / <alpha-value>)",
          400: "oklch(var(--mtx-turquoise-400) / <alpha-value>)",
          500: "oklch(var(--mtx-turquoise-500) / <alpha-value>)",
          600: "oklch(var(--mtx-turquoise-600) / <alpha-value>)",
          700: "oklch(var(--mtx-turquoise-700) / <alpha-value>)",
          DEFAULT: "oklch(var(--mtx-turquoise-500) / <alpha-value>)",
        },
        border: "oklch(var(--mtx-border) / <alpha-value>)",
        input: "oklch(var(--mtx-input) / <alpha-value>)",
        ring: "oklch(var(--mtx-ring) / <alpha-value>)",
        chart: {
          1: "oklch(var(--mtx-chart-1) / <alpha-value>)",
          2: "oklch(var(--mtx-chart-2) / <alpha-value>)",
          3: "oklch(var(--mtx-chart-3) / <alpha-value>)",
          4: "oklch(var(--mtx-chart-4) / <alpha-value>)",
          5: "oklch(var(--mtx-chart-5) / <alpha-value>)",
        },
      },
      boxShadow: {
        card: "var(--mtx-shadow-card)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },

          to: {
            height: "0",
          },
        },
        "collapsible-down": {
          from: { height: "0" },
          to: { height: "var(--radix-collapsible-content-height)" },
        },
        "collapsible-up": {
          from: { height: "var(--radix-collapsible-content-height)" },
          to: { height: "0" },
        },
        "slide-from-bottom": {
          "0%": { transform: "translateY(100%)" },
          "100%": { transform: "translateY(0)" },
        },
        "slide-to-bottom": {
          "0%": { transform: "translateY(0)" },
          "100%": { transform: "translateY(100%)" },
        },
        "input-open": {
          "0%": { width: "0" },
          "100%": { width: "100%" },
        },
        "input-close": {
          "0%": { width: "100%" },
          "100%": { width: "0", opacity: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "collapsible-down": "collapsible-down 0.2s ease-out",
        "collapsible-up": "collapsible-up 0.2s ease-out",
        "slide-from-bottom": "slide-from-bottom 0.50s cubic-bezier(0.32,0.72,0,1) forwards",
        "slide-to-bottom": "slide-to-bottom 0.50s cubic-bezier(0.32,0.72,0,1) forwards",
        "input-open": "input-open 0.20s ease-out forwards",
        "input-close": "input-close 0.20s ease-out forwards",
      },
      backdropContrast: {
        300: "3",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
