name: Publish Library

on:
  push:
    branches:
      - test-auth

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Verify NODE_AUTH_TOKEN
        run: |
          echo "NODE_AUTH_TOKEN length: ${#NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Verify Auth NODE_AUTH_TOKEN
        run: echo $NODE_AUTH_TOKEN
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Authenticate with npm registry
        run: npm whoami --scope=@trsys-tech
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
